### ISSUE TITLE
Scheduled backups fail with "volume doesn't implement mount"

### ISSUE THREAD

**Issue by nbriche** [flathub/org.gnome.DejaDup#19]
System has been reinstalled a month ago after a SSD failure, and a previous Deja Dup backup has been restored from a SFTP target (accessed via SSH keys).
A simple ssh succeeds, Nautilus mounts the folder with no issue. Manual backup succeeds with no issue.
But not one scheduled backup has succeeded yet, with just a notification "Backup delayed: Volume doesn't implement mount"

**Comment by nbriche** [comment]
Some time on search engines for "volume doesn't implement mount" has only unearthed bugs from last decade, with no obvious related solution.

**Comment by mikix** [comment]
Interesting! That error message usually happens if gvfs doesn't recognize the url or it's a url fragment. So something like `file://blarg` would give that error.

But if nautilus can mount it, there shouldn't be a problem. And if manual backups work, there shouldn't be a problem.

Do you have multiple Deja Dup's installed? Like one from your distro, and one via flatpak or something like that? One of them could have a bogus config and could be the one running the scheduled backups... Grasping at straws here.

**Comment by nbriche** [comment]
The multiple installation is an interesting point. The distro is EndeavourOS, replacing an Ubuntu. I installed the flatpak after searching for the app and not finding it, but it may be that restoring the whole $HOME, including obviously Deja Dup's own config files/parameters from the previous install, may have borked some of the new running install's. I've since rebooted a few times of course, but depending on how the parameter state is recorded, a simple reboot may not be enough.
It being my workstation I don't have access to it during the weekend for further tests, but when I'm back at work I'll try something I really should have done earlier: toggling scheduling off and on again and changing the frequency a few times.
With any luck it'll reset any leftovers from the last install. I'll report my findings here.

**Comment by nbriche** [comment]
The toggling and frequency changing seems to be a success: there was no error from the scheduled backup this time.
I don't know which of the two did it; maybe should have done it in two steps; test one then the other a day after. But at least I'm secure again. Thanks!
