### ISSUE TITLE
I can't enable automatic backup 

### ISSUE THREAD

**Issue by robsonjorgefernandez** [flathub/org.gnome.DejaDup#2]
Hi,

I can't enable `Automatic backup` on Fedora 31, the button is disabled.

# Flatpak
`$ flatpak --version`
`Flatpak 1.4.4`

# Deja Dup
`$ flatpak run org.gnome.DejaDup  --version`
`deja-dup 40.6`

# System
`Operating System: Fedora 31 (Workstation Edition)`
`CPE OS Name: cpe:/o:fedoraproject:fedora:31`
`Kernel: Linux 5.5.5-200.fc31.x86_64`
`Architecture: x86-64`

![image](https://user-images.githubusercontent.com/16673533/75449566-f4a38d80-594b-11ea-8932-97c13c5cead5.png)

I have another system(Ubuntu 19.10) and this issue doesn't happen.
Does anyone have any idea?

**Comment by mikix** [comment]
Because flatpak is containerized, Deja Dup can’t auto-start itself. So we use the background portal that flatpak provides to ask the system to start us automatically.

But support for that portal in GNOME is pretty new. Maybe 31 doesn’t have full support? There is a section of the system settings that lets you control what permissions flatpak apps have. Is there anything there about starting in the background?

**Comment by robsonjorgefernandez** [comment]
I did reset the permission with ` flatpak permission-reset org.gnome.DejaDup` to make it prompt again.

Then start the app again and allow it.
![image](https://user-images.githubusercontent.com/16673533/75474376-a5725280-5975-11ea-8c7f-40af724e4c9a.png)

Thanks you!
