### ISSUE TITLE
Keeps asking for auth token with google drive

### ISSUE THREAD

**Issue by ctron** [flathub/org.gnome.DejaDup#20]
Since a recent update (not sure which) it asks for the google drive authentication for every step in the process.

It feels like it is missing/loosing the token after every step (checking, preparing, backing up, validating).

**Comment by mikix** [comment]
Sounds like it's not able to store the password in libsecret -- wonder why that would happen... 

You can see what keys, if any, a flatpak app has by installing [Key Rack](https://flathub.org/apps/details/app.drey.KeyRack). (You need a separate app because flatpak apps store passwords in a weird encrypted format.) Does Deja Dup have anything in there?

**Comment by ctron** [comment]
No sure what changed, definitely a few flatpak updates (both OS and platforms) took place. Now the issue is gone, but now the application is in light mode (used to be in dark mode). Anyway, the issue is gone.

**Comment by mikix** [comment]
Ah interesting. The light mode thing is because we updated to using libadwaita and it requires a fairly modern system to provide correct dark/light theme info.

We have some heuristics to try to detect the theme anyway on older machines, but sounds like it’s not working on yours. Sorry.

**Comment by ctron** [comment]
No worries, I actually prefer most applications in light mode, but the desktop in dark mode :)

**Comment by ctron** [comment]
I am not sure when it happened, but the application is in this state again.

I installed Key Rack, and found no application in there. I also installed "Flat Seal" to check for permissions, but couldn't find anything that looked like "lib secret".

**Comment by mikix** [comment]
What's your desktop environment? KDE?

**Comment by ctron** [comment]
> What's your desktop environment? KDE?

Yes, KDE.

**Comment by mikix** [comment]
I am having trouble finding the context for this, but my understanding is that KDE still does not integrate libsecret support into KWallet: https://invent.kde.org/frameworks/kwallet/-/merge_requests/11

I think there are alternate secret stores for kde like KeePassXC that do support it? But this is a known issue for KDE at the moment. Sorry. I'll close, because there's not much I can easily do about it.
