### ISSUE TITLE
Backup Automatically cannot be enabled

### ISSUE THREAD

**Issue by gabrieletassoni** [flathub/org.gnome.DejaDup#27]
Hi,
I cannot activate the automatic backup in my Ubuntu Budgie, here is the lsb_release information:

```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 23.10
Release:	23.10
Codename:	mantic
```

Deja Dup version is **45.1**, installed via Flathub:

![image](https://github.com/flathub/org.gnome.DejaDup/assets/11076471/bbe20bfc-72e6-4d5f-a7e2-7a659a48c434)

Here is the error:

![image](https://github.com/flathub/org.gnome.DejaDup/assets/11076471/8f396f08-257f-4cc9-8e95-11a8399a3b96)

Here the configuration from Flatseal (I've applied them from other, older, issues, now closed in this same repository, but they don't seem to work anymore):

![image](https://github.com/flathub/org.gnome.DejaDup/assets/11076471/a3eb0bb7-4529-45bf-8354-c9b72b9b967e)

![image](https://github.com/flathub/org.gnome.DejaDup/assets/11076471/50dd9f6c-1d18-4540-b8b3-2b01bb32bfa8)

And this is from the Applications Setting:

![image](https://github.com/flathub/org.gnome.DejaDup/assets/11076471/5784eff1-76c7-4220-9926-c1f9648a5427)

I also tried to run these commands:

```bash
flatpak permission-reset org.gnome.DejaDup
flatpak permission-set background background org.gnome.DejaDup yes
```

Re-opening the Backup application after each one, but the error keeps showing and the Automation of the Backups cannot be enabled.

How can I solve this?

Thank you very much,
Gabriele

**Comment by mikix** [comment]
Hello! This is probably due to an unimplemented backend for the Background xdg desktop portal...?

The rough flow here is:
- Deja Dup asks the XDG Background desktop portal over DBus.
- Then the xdg portal checks those flatpak permissions bits you see in flatseal and then [sends](https://github.com/flatpak/xdg-desktop-portal/blob/main/src/background.c#L796) the request over to a desktop-specific implementation portal
- That portal does whatever makes sense for the current desktop (like actually setting whatever config will launch deja-dup on desktop startup) -- in GNOME it [drops an xdg autostart desktop file](https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/blob/main/src/background.c?ref_type=heads#L210) in the user's home dir

I'm _guessing_ Budge doesn't have a implementation portal and so the Backend request that deja-dup makes errors out.

I see some discussion of a Budgie portal backend here: https://github.com/BuddiesOfBudgie/budgie-desktop/discussions/428 (but it makes it sound like they are using the gnome portals in the meantime?)

**Comment by mikix** [comment]
You may see some improvement if you manually install xdg-desktop-portal-gnome, but I don't know if that will conflict with anything Budgie is doing.

**Comment by gabrieletassoni** [comment]
Hi, thank you for the answer,
I installed via apt the xdg-desktop-portal-gnome it didn't broke the system, but DejaDup still cannot automatically schedule runs (same errors as per bug report, nothing changed).

**Comment by gabrieletassoni** [comment]
Also rebooted and tried to activate automatic backups, but it still throws the same error.

**Comment by mikix** [comment]
OK I tested this and can confirm the same behavior you see. And that installing `xdg-desktop-portal-gnome` doesn't fix it (although it does add a long delay to app launch and elsewhere for me).

But... manually running `/usr/libexec/xdg-desktop-portal-gnome` in the terminal makes everything work as expected. So I think my assessment about Budgie missing a Background portal is correct. And there's some (mis?)configuration that prevents the GNOME portal from working/launching in Budgie by default.

I think this is not a thing we can reasonably fix. From inside the flatpak, we are doing "the right thing" to request autostarting from the desktop.

However, I do think we can be a lot nicer in the messaging. I'll try to think up a clearer message.

**Comment by mikix** [comment]
How does this feel? It's not entirely actionable by the user, but I think it's a clearer explanation of what's happening. And might turn them towards the correct source (support tickets for their specific desktop environment).

![image](https://github.com/flathub/org.gnome.DejaDup/assets/1196901/f1550ea7-dea4-44d3-81f0-3d885360acf6)

**Comment by fossfreedom** [comment]
FYI - budgie desktop defaults to the gtk portal  which on Ubuntu Budgie is installed by default.

**Comment by mikix** [comment]
Correct, but the gtk portal package does not provide the Background portal implementation in question here. That’s normally provided by the gnome portal package.

**Comment by mikix** [comment]
Fixed in https://gitlab.gnome.org/World/deja-dup/-/commit/62620b5e62fab5cf10339f97fdbaf3b7affde6f6

Thanks for your help!
