### ISSUE TITLE
[Feature Request] Being able to select max file size for backups

### ISSUE THREAD

**Issue by Toadfield** [flathub/org.gnome.DejaDup#9]
So that if that max file size is reached,that you get a warning message.

**Comment by mikix** [comment]
I agree that would be nice. It's not easily accomplished with the current technical underpinnings. Duplicity, the tool that Deja Dup uses under the covers, does not provide that capability internally.

We could try to add the feature on top of Duplicity, by asking it to clean up old backups as we get close to size limit. But Duplicity also doesn't make it very easy to know how big the backup we are about to make is going to be. So we can't easily know how much room to make.

This sort of feature is provided by next-gen backup tools like restic and borg. I'm looking into supporting them too. But that's a ways off.

I'll close this ticket because it isn't directly actionable, but know that I sympathize and there are plans in the works to eventually enable this sort of feature.
